// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5VgCxw7UknAsHHfK5JOMT0ntRmC3jc0U',
    appId: '1:951622306229:android:c97f8dfb0acad8b0f971fc',
    messagingSenderId: '951622306229',
    projectId: 'studyn-5bff0',
    storageBucket: 'studyn-5bff0.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFVkh4SRVCphPDlkVdF45jjbK_wwl45ZY',
    appId: '1:951622306229:ios:93888477521baebbf971fc',
    messagingSenderId: '951622306229',
    projectId: 'studyn-5bff0',
    storageBucket: 'studyn-5bff0.firebasestorage.app',
    iosBundleId: 'com.neerjournal.studyn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDET3-XsfGPRpdP9zqdSQ3crDBSaNJgu9Y',
    appId: '1:951622306229:web:ec1fbb77a80f7edaf971fc',
    messagingSenderId: '951622306229',
    projectId: 'studyn-5bff0',
    authDomain: 'studyn-5bff0.firebaseapp.com',
    storageBucket: 'studyn-5bff0.firebasestorage.app',
    measurementId: 'G-7Y8V17MBWD',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyD5VgCxw7UknAsHHfK5JOMT0ntRmC3jc0U',
    appId: '1:951622306229:web:ec1fbb77a80f7edaf971fc',
    messagingSenderId: '951622306229',
    projectId: 'studyn-5bff0',
    authDomain: 'studyn-5bff0.firebaseapp.com',
    storageBucket: 'studyn-5bff0.firebasestorage.app',
    measurementId: 'G-7Y8V17MBWD',
  );
}
